In [1]:
import numpy as np

In [12]:
x = [8.0, 9.0, 9.5, 11.0]
y = [2.079442, 2.197225, 2.251292, 2.397895]

n = len(x)

ST = np.zeros((n, n))
"""
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
"""

for k in range(n):
    ST[k][0] = y[k]

"""
[[2.079442 0.       0.       0.      ]
 [2.197225 0.       0.       0.      ]
 [2.251292 0.       0.       0.      ]
 [2.397895 0.       0.       0.      ]]
"""

for k in range(1, n): # kolom
    for i in range(0, n-k): # baris
        ST[i][k] = (ST[i+1][k-1] - ST[i][k-1]) / (x[i+k] - x[i])
"""
[[ 2.07944200e+00  1.17783000e-01 -6.43266667e-03  4.11111111e-04]
 [ 2.19722500e+00  1.08134000e-01 -5.19933333e-03  0.00000000e+00]
 [ 2.25129200e+00  9.77353333e-02  0.00000000e+00  0.00000000e+00]
 [ 2.39789500e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
"""

# misalkan yang mau diprediksi adalah x_input = 9.2
x_input = 9.2

jumlah = ST[0][0] # a0

for i in range(1, n):
    suku = 0
    a_i = ST[0][i] # a ke i
    suku = suku + a_i
    for k in range(0, i-1):
        suku = suku * (x_input-x[k])

    jumlah = jumlah + suku

newton = jumlah 
print(newton)


2.1896044666666663


In [15]:
# Versi fungsinya

def membuat_ST(x, y):
    n = len(x)
    ST = np.zeros((n, n))
    for k in range(n):
        ST[k][0] = y[k]
    for k in range(1, n):  # kolom
        for i in range(0, n-k):  # baris
            ST[i][k] = (ST[i+1][k-1] - ST[i][k-1]) / (x[i+k] - x[i])
    
    return ST
    
def newton_polynom(x_input, ST):
    jumlah = ST[0][0]  # a0
    n = len(ST[0])
    for i in range(1, n):
        suku = 0
        a_i = ST[0][i]  # a ke i
        suku = suku + a_i
        for k in range(0, i-1):
            suku = suku * (x_input-x[k])

        jumlah = jumlah + suku

    y_newton = jumlah
    return y_newton